ALTER TABLE "UserSettings"
ADD COLUMN "speechVoiceUri" TEXT,
ADD COLUMN "speechRate" DOUBLE PRECISION NOT NULL DEFAULT 0.8,
ADD COLUMN "speechAutoplay" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "soundFeedback" BOOLEAN NOT NULL DEFAULT false;
